FROM public.ecr.aws/bitnami/node:20 AS build
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .

FROM public.ecr.aws/bitnami/node:20
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3010
CMD ["npm", "start"]
