FROM node:20-alpine AS build
WORKDIR /app
RUN apk update && apk upgrade
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production=false
COPY . .
RUN yarn build

FROM node:20-alpine
WORKDIR /app
RUN apk update && apk upgrade
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production=true && yarn cache clean
COPY --from=build /app/dist ./dist
COPY --from=build /app/libs ./libs
EXPOSE 3010
CMD ["node", "dist/microservices/order/main"]
