FROM public.ecr.aws/nginx/nginx:mainline-alpine AS build

COPY ./reverseproxy/index.html /etc/nginx/html/index.html
COPY ./reverseproxy/nginx.template /etc/nginx/nginx.template 

RUN chmod 644 /etc/nginx/html/index.html /etc/nginx/nginx.template

ENTRYPOINT [ "sh", "-c", "envsubst '${NAMESPACE}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'" ]

EXPOSE 80