#!/bin/bash -e

export CDK_PARAM_SYSTEM_ADMIN_EMAIL="$1"

if [[ -z "$CDK_PARAM_SYSTEM_ADMIN_EMAIL" ]]; then
  echo "Please provide system admin email"
  exit 1
fi

# Load API keys from file generated by init-install.sh
API_KEYS_FILE=".api-keys.env"

if [[ -f "$API_KEYS_FILE" ]]; then
  echo "Loading API keys from $API_KEYS_FILE"
  source "$API_KEYS_FILE"
else
  echo "Error: API keys file not found. Please run init-install.sh first."
  exit 1
fi

# Validate that API keys are loaded
if [[ -z "$CDK_PARAM_API_KEY_PREMIUM_TIER_PARAMETER" ]] || [[ -z "$CDK_PARAM_API_KEY_ADVANCED_TIER_PARAMETER" ]] || [[ -z "$CDK_PARAM_API_KEY_BASIC_TIER_PARAMETER" ]]; then
  echo "Error: API keys not loaded properly from $API_KEYS_FILE"
  echo "Please run init-install.sh again to regenerate API keys."
  exit 1
fi

echo "Using API keys from init-install.sh:"
echo "Premium API Key: $CDK_PARAM_API_KEY_PREMIUM_TIER_PARAMETER"
echo "Advanced API Key: $CDK_PARAM_API_KEY_ADVANCED_TIER_PARAMETER"
echo "Basic API Key: $CDK_PARAM_API_KEY_BASIC_TIER_PARAMETER"

REGION=$(aws ec2 describe-availability-zones --output text --query 'AvailabilityZones[0].[RegionName]')  # Region setting
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

export CDK_PARAM_S3_BUCKET_NAME="saas-reference-architecture-ecs-$ACCOUNT_ID-$REGION"
CDK_SOURCE_NAME="source.tar.gz"

VERSIONS=$(aws s3api list-object-versions --bucket "$CDK_PARAM_S3_BUCKET_NAME" --prefix "$CDK_SOURCE_NAME" --query 'Versions[?IsLatest==`true`].{VersionId:VersionId}' --output text 2>&1)
export CDK_PARAM_COMMIT_ID=$(echo "$VERSIONS" | awk 'NR==1{print $1}')

cd ../server

# npx cdk bootstrap
export CDK_PARAM_TIER='basic'


npm install
#npx cdk deploy --all --require-approval=never
npx cdk deploy \
    controlplane-stack \
    core-appplane-stack \
    --require-approval never #--verbose ##--concurrency 10 --asset-parallelism true

# Get SaaS application url
ADMIN_SITE_URL=$(aws cloudformation describe-stacks --stack-name shared-infra-stack --query "Stacks[0].Outputs[?OutputKey=='adminSiteUrl'].OutputValue" --output text)
APP_SITE_URL=$(aws cloudformation describe-stacks --stack-name shared-infra-stack --query "Stacks[0].Outputs[?OutputKey=='appSiteUrl'].OutputValue" --output text)
echo "Admin site url: $ADMIN_SITE_URL"
echo "Application site url: $APP_SITE_URL"